### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by RaonHaonKIM** [clovaai/stargan-v2#100]
안녕하세요, 우선 정말 좋은 코드를 공유해주셔서 감사드립니다.
예제로 공개해주신 코드를 돌려보았는데 쿠다 메모리가 초과됐다는 에러가 발생합니다.
Hello, first of all, thank you for sharing such a good code.
I returned the code you released as an example, but there is an error that the Cuda memory has been exceeded.

C:\Users\user\anaconda3\envs\stargan-v2\lib\site-packages\torch\nn\functional.py:2506: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "main.py", line 182, in <module>
    main(args)
  File "main.py", line 59, in main
    solver.train(loaders)
  File "C:\Users\user\stargan\stargan-v2\core\solver.py", line 123, in train
    nets, args, x_real, y_org, y_trg, z_trgs=[z_trg, z_trg2], masks=masks)
  File "C:\Users\user\stargan\stargan-v2\core\solver.py", line 259, in compute_g_loss
    x_rec = nets.generator(x_fake, s_org, masks=masks)
  File "C:\Users\user\anaconda3\envs\stargan-v2\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\user\stargan\stargan-v2\core\model.py", line 181, in forward
    x = block(x, s)
  File "C:\Users\user\anaconda3\envs\stargan-v2\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\user\stargan\stargan-v2\core\model.py", line 117, in forward
    out = self._residual(x, s)
  File "C:\Users\user\stargan\stargan-v2\core\model.py", line 111, in _residual
    x = self.norm2(x, s)
  File "C:\Users\user\anaconda3\envs\stargan-v2\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\user\stargan\stargan-v2\core\model.py", line 77, in forward
    return (1 + gamma) * self.norm(x) + beta
RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 8.00 GiB total capacity; 6.33 GiB already allocated; 24.12 MiB free; 6.45 GiB reserved in total by PyTorch)

이렇게 오류가 뜨는데 해결 방법을 알고 싶습니다 ㅠㅠ
I'd like to know how to solve this error.

**Comment by 1170300814** [comment]
use small batchsize
