### ISSUE TITLE
PILLOW_VERSION is missing on pillow==7.0.0

### ISSUE THREAD

**Issue by bobiblazeski** [clovaai/stargan-v2#12]
Running command to generate images fails on:

```
File "/home/bobi/.local/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 5, in <module>
    from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
ImportError: cannot import name 'PILLOW_VERSION'
(stargan-v2) bobi@strix:~/Desktop/stargan-v2$ python 
Python 3.6.7 |Anaconda, Inc.| (default, Oct 23 2018, 19:16:44) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PIL
>>> PIL.PILLOW_VERSION
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'PIL' has no attribute 'PILLOW_VERSION
```

I works with 

`pip install "pillow<7"`

**Comment by yunjey** [comment]
@bobiblazeski You should install packages using either ``pip install -r torch==1.4.0 torchvision==0.5.0 pillow==7.0.0`` or ``pip install -r torch==1.0.0 torchvision==0.2.0 pillow==6.1``.

**Comment by bobiblazeski** [comment]
Will do thanks
