### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by lzkforlearn** [clovaai/stargan-v2#164]
I try python main.py
there is a error:
Traceback (most recent call last):
  File "C:\Users\19099\Desktop\stargan-v2-master\main.py", line 182, in <module>
    main(args)
  File "C:\Users\19099\Desktop\stargan-v2-master\main.py", line 37, in main
    solver = Solver(args)
  File "C:\Users\19099\Desktop\stargan-v2-master\core\solver.py", line 58, in __init__
    self.ckptios = [CheckpointIO(ospj(args.checkpoint_dir, '{:06d}_nets_ema.ckpt'), data_parallel=True, **self.nets_ema)]
  File "C:\Users\19099\Desktop\stargan-v2-master\core\checkpoint.py", line 17, in __init__
    os.makedirs(os.path.dirname(fname_template), exist_ok=True)
  File "C:\Users\19099\anaconda3\envs\lzk\lib\os.py", line 223, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: '{:'
how to solve it ?

**Comment by QinDer** [comment]
How to solve this problem?I have the same problem.

**Comment by SubeBila** [comment]
Is your model file path correct, try checking it.
