### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by iampranav-ai** [clovaai/stargan-v2#35]
Getting the issue in Windows 10 CMD
I tried ffmpeg uninstall and install.
Nothing works.

Error message:

Traceback (most recent call last):
File "main.py", line 182, in
main(args)
File "main.py", line 37, in main
solver = Solver(args)
File "C:\Users\xxx\stargan-v2\core\solver.py", line 58, in init
self.ckptios = [CheckpointIO(ospj(args.checkpoint_dir, '{:06d}_nets_ema.ckpt'), **self.nets_ema)]
File "C:\Users\xxx\stargan-v2\core\checkpoint.py", line 17, in init
os.makedirs(os.path.dirname(fname_template), exist_ok=True)
File "C:\Users\xxx.conda\envs\stargan-v2\lib\os.py", line 220, in makedirs
mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: '{:'

**Comment by Yvonne0413** [comment]
this problem was already solved in #3
