### ISSUE TITLE
AttributeError: 'InputFetcher' object has no attribute 'iter'

### ISSUE THREAD

**Issue by GuoQuanhao** [clovaai/stargan-v2#84]
Hi, dear author, I got the following error
```
python main.py --mode train --num_domains 3 --w_hpf 0 \
               --batch_size 1 \
               --lambda_reg 1 --lambda_sty 1 --lambda_ds 2 --lambda_cyc 1 \
               --train_img_dir data/afhq/train \
               --val_img_dir data/afhq/val
```

Win10 platform
pytorch1.6.0
```
Traceback (most recent call last):
  File "E:\stargan-v2-master\core\data_loader.py", line 180, in _fetch_inputs
    x, y = next(self.iter)
AttributeError: 'InputFetcher' object has no attribute 'iter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 182, in <module>
    main(args)
  File "main.py", line 59, in main
    solver.train(loaders)
  File "E:\stargan-v2-master\core\solver.py", line 100, in train
    inputs = next(fetcher)
  File "E:\stargan-v2-master\core\data_loader.py", line 195, in __next__
    x, y = self._fetch_inputs()
  File "E:\stargan-v2-master\core\data_loader.py", line 182, in _fetch_inputs
    self.iter = iter(self.loader)
  File "E:\Anaconda3\envs\pytorch1.6.0\lib\site-packages\torch\utils\data\dataloader.py", line 291, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "E:\Anaconda3\envs\pytorch1.6.0\lib\site-packages\torch\utils\data\dataloader.py", line 737, in __init__
    w.start()
  File "E:\Anaconda3\envs\pytorch1.6.0\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "E:\Anaconda3\envs\pytorch1.6.0\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "E:\Anaconda3\envs\pytorch1.6.0\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "E:\Anaconda3\envs\pytorch1.6.0\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "E:\Anaconda3\envs\pytorch1.6.0\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'get_train_loader.<locals>.<lambda>'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Anaconda3\envs\pytorch1.6.0\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "E:\Anaconda3\envs\pytorch1.6.0\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
```
what should I do  /(ㄒoㄒ)/~~

**Comment by cym860113** [comment]
I have the same problem...
I think lambda objects cannot be pickled on Windows
After I change the num_worker from 4 to 0,  it can work!
